version: 1.0.{build}
os: Visual Studio 2015
test: off
clone_folder: C:\projects\LevelSyn
branches:
  only:
    - master
build_script:
  - echo Running cmake...
  - cd c:\projects\LevelSyn\
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - set MSBuildOptions=/v:m /p:Configuration=Release /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% LevelSyn.sln
