language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

compiler:  
    - gcc
    - clang

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install cmake   ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libboost; fi
    - mkdir build
    - cd build
    - cmake ..

script: make 
