language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

compiler:  
    - gcc
    - clang

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake   ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
    - mkdir build
    - cd build
    - cmake ..

script: make 
